import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  appContainer: { flex: 1, backgroundColor: '#f9f9f9' },
  appHeader: { position: 'absolute', top: 0, left: 0, right: 0, height: 64, backgroundColor: '#f9f9f9', borderBottomWidth: 1, borderBottomColor: '#f3f4f6', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 24, zIndex: 50 },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  appTitle: { fontSize: 20, fontWeight: '900', letterSpacing: -1, textTransform: 'uppercase', color: '#1a1c1c' },
  profileContainer: { width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(57, 255, 20, 0.2)', borderWidth: 2, borderColor: '#39ff14', overflow: 'hidden' },
  profileImg: { width: '100%', height: '100%' },
  mainContent: { paddingTop: 64, paddingBottom: 96, flex: 1 },
  bottomNav: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: '#1a1c1c', height: 80, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingHorizontal: 16, zIndex: 50, shadowColor: '#39ff14', shadowOffset: { width: 0, height: -10 }, shadowOpacity: 0.15, shadowRadius: 40, elevation: 20 },
  navBtn: { alignItems: 'center', justifyContent: 'center', gap: 4, paddingVertical: 8, paddingHorizontal: 16, borderRadius: 12 },
  navBtnActive: { backgroundColor: '#2f3131' },
  navLabel: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.6, color: 'rgba(255, 255, 255, 0.6)' },
  navLabelActive: { color: '#39ff14' },
  screenWrapper: { paddingTop: 32, paddingHorizontal: 24, alignSelf: 'center', width: '100%', maxWidth: 512, flex: 1 },
  scrollContent: { paddingBottom: 48 },
  scanScreen: { flex: 1, paddingTop: 32, paddingHorizontal: 24, alignItems: 'center' },
  heroTitle: { fontSize: 64, fontWeight: '900', lineHeight: 54, letterSpacing: -3.2, textTransform: 'uppercase', marginBottom: 48, alignSelf: 'flex-start', color: '#1a1c1c' },
  radarWrapper: { position: 'relative', width: '100%', aspectRatio: 1, maxWidth: 340 },
  radarGlow: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, backgroundColor: 'rgba(57, 255, 20, 0.15)', borderRadius: 170 },
  radarCard: { width: '100%', height: '100%', backgroundColor: '#1a1c1c', borderRadius: 24, alignItems: 'center', justifyContent: 'center', padding: 32, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 25 }, shadowOpacity: 0.25, shadowRadius: 50, elevation: 15 },
  radarAnimationContainer: { position: 'relative', width: 192, height: 192, alignItems: 'center', justifyContent: 'center', marginBottom: 40 },
  radarRing: { position: 'absolute', width: '100%', height: '100%', borderRadius: 96, borderWidth: 2 },
  radarCenter: { width: 96, height: 96, backgroundColor: '#39ff14', borderRadius: 48, alignItems: 'center', justifyContent: 'center', shadowColor: '#39ff14', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.5, shadowRadius: 40, elevation: 10 },
  scanningTextWrapper: { alignItems: 'center' },
  scanningText: { color: '#39ff14', fontWeight: '900', fontSize: 20, letterSpacing: -0.5, textTransform: 'uppercase', lineHeight: 22, marginBottom: 16, textAlign: 'center' },
  scanningDots: { flexDirection: 'row', justifyContent: 'center', gap: 6, height: 10 },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#39ff14' },
  corner: { position: 'absolute', width: 24, height: 24, borderColor: 'rgba(57, 255, 20, 0.4)' },
  topLeft: { top: 24, left: 24, borderTopWidth: 2, borderLeftWidth: 2 },
  topRight: { top: 24, right: 24, borderTopWidth: 2, borderRightWidth: 2 },
  bottomLeft: { bottom: 24, left: 24, borderBottomWidth: 2, borderLeftWidth: 2 },
  bottomRight: { bottom: 24, right: 24, borderBottomWidth: 2, borderRightWidth: 2 },
  offlineNotice: { marginTop: 48, flexDirection: 'row', alignItems: 'center', gap: 8 },
  offlineText: { color: '#9ca3af', fontWeight: '700', fontSize: 10, textTransform: 'uppercase', letterSpacing: 1.6 },
  statusIndicator: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 32 },
  liveDotContainer: { width: 12, height: 12, justifyContent: 'center', alignItems: 'center' },
  liveDotCore: { width: '100%', height: '100%', borderRadius: 6, backgroundColor: '#39ff14' },
  statusLabel: { fontSize: 12, fontWeight: '900', letterSpacing: 1.2, textTransform: 'uppercase', color: '#6b7280' },
  tokenCard: { backgroundColor: '#1a1c1c', borderRadius: 40, padding: 48, alignItems: 'center', marginBottom: 48, shadowColor: '#000', shadowOffset: { width: 0, height: 20 }, shadowOpacity: 0.1, shadowRadius: 25, elevation: 5 },
  tokenSubtitle: { color: '#39ff14', fontWeight: '900', letterSpacing: 3.2, fontSize: 12, textTransform: 'uppercase', marginBottom: 16 },
  tokenTitle: { color: '#fff', fontWeight: '900', fontSize: 72, lineHeight: 72, letterSpacing: -3.6, marginBottom: 24, textAlign: 'center' },
  queuePosition: { backgroundColor: 'rgba(57, 255, 20, 0.1)', borderWidth: 1, borderColor: 'rgba(57, 255, 20, 0.2)', borderRadius: 20, paddingVertical: 8, paddingHorizontal: 24 },
  queuePositionText: { color: '#39ff14', fontWeight: '700', fontSize: 14 },
  progressContainer: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 64, paddingHorizontal: 16 },
  progressLineBg: { position: 'absolute', top: 20, left: 32, right: 32, height: 2, backgroundColor: '#e5e7eb', zIndex: -1 },
  progressLineActive: { position: 'absolute', top: 20, left: 32, width: '50%', height: 2, backgroundColor: '#39ff14', zIndex: -1 },
  progressStep: { alignItems: 'center', gap: 12 },
  stepCircle: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#f3f4f6' },
  stepCircleActive: { backgroundColor: '#39ff14', borderColor: 'transparent', shadowColor: '#39ff14', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.4, shadowRadius: 20, elevation: 8 },
  stepTextContainer: { alignItems: 'center' },
  stepLabel: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: -0.4, color: '#9ca3af' },
  stepLabelActive: { color: '#000' },
  stepSub: { fontSize: 8, color: '#9ca3af', fontWeight: '700' },
  orderDetailsCard: { backgroundColor: '#f3f4f6', borderRadius: 24, padding: 24 },
  orderHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  orderHeaderTitle: { fontWeight: '900', fontSize: 18, textTransform: 'uppercase', letterSpacing: -0.4, color: '#1a1c1c' },
  orderId: { fontSize: 10, backgroundColor: '#e5e7eb', paddingVertical: 4, paddingHorizontal: 12, borderRadius: 12, fontWeight: '700', color: '#1a1c1c' },
  orderItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  itemInfoLeft: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  itemImgContainer: { width: 64, height: 64, backgroundColor: '#1a1c1c', borderRadius: 16, overflow: 'hidden' },
  itemImg: { width: '100%', height: '100%', opacity: 0.8 },
  itemName: { fontWeight: '900', textTransform: 'uppercase', fontSize: 14, color: '#1a1c1c' },
  itemMods: { fontSize: 12, color: '#6b7280', fontWeight: '500' },
  itemPrice: { fontWeight: '900', fontSize: 20, color: '#39ff14', backgroundColor: '#1a1c1c', paddingVertical: 4, paddingHorizontal: 12, borderRadius: 8 },
  adminHeaderSection: { marginBottom: 48 },
  adminSubtitle: { fontSize: 10, fontWeight: '900', letterSpacing: 3.2, textTransform: 'uppercase', color: '#39ff14', marginBottom: 8 },
  adminTitle: { fontSize: 56, fontWeight: '900', lineHeight: 50, letterSpacing: -2.2, textTransform: 'uppercase', color: '#1a1c1c' },
  adminGrid: { marginBottom: 48, gap: 24 },
  ocrUploadCard: { backgroundColor: 'rgba(57, 255, 20, 0.05)', borderRadius: 32, borderWidth: 2, borderStyle: 'dashed', borderColor: '#d1d5db', padding: 48, alignItems: 'center' },
  ocrIcon: { marginBottom: 24 },
  ocrTitle: { fontSize: 20, fontWeight: '900', textTransform: 'uppercase', letterSpacing: -0.4, marginBottom: 8, color: '#1a1c1c' },
  ocrDesc: { fontSize: 10, fontWeight: '700', color: '#9ca3af', textTransform: 'uppercase', letterSpacing: 1.6 },
  statsCard: { backgroundColor: '#1a1c1c', padding: 32, borderRadius: 32, justifyContent: 'space-between' },
  statsLabel: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.6, opacity: 0.6, color: '#fff', marginBottom: 4, marginTop: 16 },
  statsValue: { fontSize: 36, fontWeight: '900', fontStyle: 'italic', color: '#fff' },
  statsBottom: { marginTop: 32 },
  confidenceWrapper: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' },
  confidenceText: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.6, opacity: 0.6, color: '#fff' },
  confidenceValue: { fontSize: 24, fontWeight: '900', color: '#39ff14' },
  confidenceBarBg: { height: 48, width: 6, backgroundColor: 'rgba(255, 255, 255, 0.1)', borderRadius: 4, overflow: 'hidden' },
  confidenceBarFill: { height: '98%', width: '100%', backgroundColor: '#39ff14' },
  inventoryHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 32 },
  inventoryTitle: { fontSize: 24, fontWeight: '900', textTransform: 'uppercase', letterSpacing: -0.4, color: '#1a1c1c' },
  exportBtn: { paddingVertical: 8, paddingHorizontal: 24, backgroundColor: '#e5e7eb', borderRadius: 12 },
  exportBtnText: { color: '#000', fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.6 },
  inventoryList: { gap: 16 },
  inventoryRow: { flexDirection: 'row', alignItems: 'center', padding: 24, borderRadius: 16, backgroundColor: '#1a1c1c' },
  inventoryRowApproved: { backgroundColor: '#f3f4f6' },
  invColMain: { flex: 2 },
  invName: { fontWeight: '900', textTransform: 'uppercase', fontSize: 18, letterSpacing: -0.4, color: '#fff' },
  invCat: { fontSize: 10, textTransform: 'uppercase', color: 'rgba(255, 255, 255, 0.4)' },
  textMuted: { color: '#9ca3af' },
  invColPrice: { flex: 1, textAlign: 'center', fontWeight: '700', color: 'rgba(255, 255, 255, 0.6)' },
  invColRec: { flex: 1, textAlign: 'center', fontWeight: '900', fontSize: 20, fontStyle: 'italic', color: '#39ff14' },
  invColAction: { flex: 1, alignItems: 'flex-end' },
  approvedBadge: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  approvedText: { color: '#9ca3af', fontWeight: '900', fontSize: 10, textTransform: 'uppercase', fontStyle: 'italic' },
  approveBtn: { backgroundColor: '#39ff14', paddingVertical: 8, paddingHorizontal: 20, borderRadius: 12 },
  approveBtnText: { color: '#000', fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.6 },
  menuScrollContent: { paddingBottom: 160 },
  priorityBanner: { backgroundColor: '#39ff14', paddingVertical: 12, paddingHorizontal: 24, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', zIndex: 40, shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.1, shadowRadius: 15, elevation: 5 },
  bannerLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  bannerText: { color: '#000', fontWeight: '900', fontSize: 10, textTransform: 'uppercase', letterSpacing: 1.6 },
  bannerTimer: { backgroundColor: '#000', paddingVertical: 4, paddingHorizontal: 12, borderRadius: 12 },
  bannerTimerText: { color: '#39ff14', fontSize: 10, fontWeight: '900' },
  happyHourBanner: { backgroundColor: '#1a1c1c', paddingVertical: 16, paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: 'rgba(255, 255, 255, 0.05)' },
  hhLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  hhText: { color: '#fff', fontWeight: '900', fontSize: 18, letterSpacing: -0.8, textTransform: 'uppercase', fontStyle: 'italic' },
  hhBadge: { color: '#39ff14', fontSize: 9, fontWeight: '900', letterSpacing: 1.6, backgroundColor: 'rgba(57, 255, 20, 0.1)', paddingVertical: 4, paddingHorizontal: 8, borderRadius: 4, borderWidth: 1, borderColor: 'rgba(57, 255, 20, 0.2)', textTransform: 'uppercase' },
  foodGrid: { padding: 24, gap: 32 },
  foodCard: { backgroundColor: '#1a1c1c', borderRadius: 24, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 25 }, shadowOpacity: 0.25, shadowRadius: 50, elevation: 15 },
  foodImgContainer: { aspectRatio: 1.33, overflow: 'hidden' },
  fastBadgeWrapper: { position: 'absolute', top: 16, left: 16, zIndex: 10 },
  fastBadge: { backgroundColor: '#39ff14', flexDirection: 'row', alignItems: 'center', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 8, gap: 6 },
  fastBadgeText: { color: '#000', fontSize: 9, fontWeight: '900' },
  foodImg: { width: '100%', height: '100%', opacity: 0.9 },
  foodInfo: { padding: 32 },
  foodHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  foodName: { fontWeight: '900', fontSize: 24, letterSpacing: -0.8, textTransform: 'uppercase', fontStyle: 'italic', color: '#fff', flex: 1, marginRight: 8 },
  foodPricing: { alignItems: 'flex-end' },
  foodPrice: { color: '#39ff14', fontWeight: '900', fontSize: 30, letterSpacing: -0.8 },
  foodOldPrice: { color: 'rgba(255, 255, 255, 0.3)', textDecorationLine: 'line-through', fontSize: 12, fontWeight: '700' },
  foodDesc: { color: 'rgba(255, 255, 255, 0.5)', fontSize: 14, fontWeight: '500', marginBottom: 24, lineHeight: 22 },
  addToTrayBtn: { backgroundColor: '#fff', padding: 16, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  addToTrayText: { color: '#000', fontWeight: '900' },
  checkoutFabContainer: { position: 'absolute', bottom: 96, left: 0, right: 0, alignItems: 'center', zIndex: 50 },
  checkoutFab: { width: '90%', maxWidth: 448, backgroundColor: '#39ff14', paddingVertical: 20, paddingHorizontal: 32, borderRadius: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', shadowColor: '#39ff14', shadowOffset: { width: 0, height: 20 }, shadowOpacity: 0.5, shadowRadius: 50, elevation: 20 },
  checkoutText: { textTransform: 'uppercase', letterSpacing: 3.2, fontSize: 12, fontWeight: '900', color: '#000' },
  checkoutAmount: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  checkoutAmountText: { fontSize: 24, letterSpacing: -0.8, fontWeight: '900', color: '#000' }
});