import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  appContainer: { flex: 1, backgroundColor: '#f9f9f9' },
  appHeader: { height: 64, backgroundColor: '#f9f9f9', borderBottomWidth: 1, borderBottomColor: '#f3f6f4', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 24, zIndex: 50 },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  appTitle: { fontSize: 20, fontWeight: '900', letterSpacing: -1, textTransform: 'uppercase', color: '#1a1c1c' },
  profileContainer: { width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(57, 255, 20, 0.2)', borderWidth: 2, borderColor: '#39ff14', overflow: 'hidden' },
  profileImg: { width: '100%', height: '100%' },
  mainContent: { paddingBottom: 20, flex: 1 },
  bottomNav: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: '#1a1c1c', height: 80, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingHorizontal: 16, zIndex: 50, shadowColor: '#39ff14', shadowOffset: { width: 0, height: -10 }, shadowOpacity: 0.15, shadowRadius: 40, elevation: 20 },
  navBtn: { alignItems: 'center', justifyContent: 'center', gap: 4, paddingVertical: 8, paddingHorizontal: 16, borderRadius: 12 },
  navBtnActive: { backgroundColor: '#2f3131' },
  navLabel: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.6, color: 'rgba(255, 255, 255, 0.6)' },
  navLabelActive: { color: '#39ff14' },
  screenWrapper: { paddingTop: 0, paddingHorizontal: 24, alignSelf: 'center', width: '100%', maxWidth: 512, flex: 1 },
  scrollContent: { paddingBottom: 48 },
  scanScreen: { flex: 1, paddingTop: 32, paddingHorizontal: 24, alignItems: 'center' },
  heroTitle: { fontSize: 64, fontWeight: '900', lineHeight: 54, letterSpacing: -3.2, textTransform: 'uppercase', marginBottom: 48, alignSelf: 'flex-start', color: '#1a1c1c' },
  radarWrapper: { position: 'relative', width: '100%', aspectRatio: 1, maxWidth: 340 },
  radarGlow: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, backgroundColor: 'rgba(57, 255, 20, 0.15)', borderRadius: 170 },
  radarCard: { width: '100%', height: '100%', backgroundColor: '#1a1c1c', borderRadius: 24, alignItems: 'center', justifyContent: 'center', padding: 32, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 25 }, shadowOpacity: 0.25, shadowRadius: 50, elevation: 15 },
  radarAnimationContainer: { position: 'relative', width: 192, height: 192, alignItems: 'center', justifyContent: 'center', marginBottom: 40 },
  radarRing: { position: 'absolute', width: '100%', height: '100%', borderRadius: 96, borderWidth: 2 },
  radarCenter: { width: 96, height: 96, backgroundColor: '#39ff14', borderRadius: 48, alignItems: 'center', justifyContent: 'center', shadowColor: '#39ff14', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.5, shadowRadius: 40, elevation: 10 },
  scanningTextWrapper: { alignItems: 'center' },
  scanningText: { color: '#39ff14', fontWeight: '900', fontSize: 20, letterSpacing: -0.5, textTransform: 'uppercase', lineHeight: 22, marginBottom: 16, textAlign: 'center' },
  scanningDots: { flexDirection: 'row', justifyContent: 'center', gap: 6, height: 10 },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#39ff14' },
  corner: { position: 'absolute', width: 24, height: 24, borderColor: 'rgba(57, 255, 20, 0.4)' },
  topLeft: { top: 24, left: 24, borderTopWidth: 2, borderLeftWidth: 2 },
  topRight: { top: 24, right: 24, borderTopWidth: 2, borderRightWidth: 2 },
  bottomLeft: { bottom: 24, left: 24, borderBottomWidth: 2, borderLeftWidth: 2 },
  bottomRight: { bottom: 24, right: 24, borderBottomWidth: 2, borderRightWidth: 2 },
  offlineNotice: { marginTop: 48, flexDirection: 'row', alignItems: 'center', gap: 8 },
  offlineText: { color: '#9ca3af', fontWeight: '700', fontSize: 10, textTransform: 'uppercase', letterSpacing: 1.6 },
  statusIndicator: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 32 },
  liveDotContainer: { width: 12, height: 12, justifyContent: 'center', alignItems: 'center' },
  liveDotCore: { width: '100%', height: '100%', borderRadius: 6, backgroundColor: '#39ff14' },
  statusLabel: { fontSize: 12, fontWeight: '900', letterSpacing: 1.2, textTransform: 'uppercase', color: '#6b7280' },
  tokenCard: { backgroundColor: '#1a1c1c', borderRadius: 40, padding: 48, alignItems: 'center', marginBottom: 48, shadowColor: '#000', shadowOffset: { width: 0, height: 20 }, shadowOpacity: 0.1, shadowRadius: 25, elevation: 5 },
  tokenSubtitle: { color: '#39ff14', fontWeight: '900', letterSpacing: 3.2, fontSize: 12, textTransform: 'uppercase', marginBottom: 16 },
  tokenTitle: { color: '#fff', fontWeight: '900', fontSize: 72, lineHeight: 72, letterSpacing: -3.6, marginBottom: 24, textAlign: 'center' },
  queuePosition: { backgroundColor: 'rgba(57, 255, 20, 0.1)', borderWidth: 1, borderColor: 'rgba(57, 255, 20, 0.2)', borderRadius: 20, paddingVertical: 8, paddingHorizontal: 24 },
  queuePositionText: { color: '#39ff14', fontWeight: '700', fontSize: 14 },
  progressContainer: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 64, paddingHorizontal: 16 },
  progressLineBg: { position: 'absolute', top: 20, left: 32, right: 32, height: 2, backgroundColor: '#e5e7eb', zIndex: -1 },
  progressLineActive: { position: 'absolute', top: 20, left: 32, width: '50%', height: 2, backgroundColor: '#39ff14', zIndex: -1 },
  progressStep: { alignItems: 'center', gap: 12 },
  stepCircle: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#f3f4f6' },
  stepCircleActive: { backgroundColor: '#39ff14', borderColor: 'transparent', shadowColor: '#39ff14', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.4, shadowRadius: 20, elevation: 8 },
  stepTextContainer: { alignItems: 'center' },
  stepLabel: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: -0.4, color: '#9ca3af' },
  stepLabelActive: { color: '#000' },
  stepSub: { fontSize: 8, color: '#9ca3af', fontWeight: '700' },
  orderDetailsCard: { backgroundColor: '#f3f4f6', borderRadius: 24, padding: 24 },
  orderHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  orderHeaderTitle: { fontWeight: '900', fontSize: 18, textTransform: 'uppercase', letterSpacing: -0.4, color: '#1a1c1c' },
  orderId: { fontSize: 10, backgroundColor: '#e5e7eb', paddingVertical: 4, paddingHorizontal: 12, borderRadius: 12, fontWeight: '700', color: '#1a1c1c' },
  orderItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  itemInfoLeft: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  itemImgContainer: { width: 64, height: 64, backgroundColor: '#1a1c1c', borderRadius: 16, overflow: 'hidden' },
  itemImg: { width: '100%', height: '100%', opacity: 0.8 },
  itemName: { fontWeight: '900', textTransform: 'uppercase', fontSize: 14, color: '#1a1c1c' },
  itemMods: { fontSize: 12, color: '#6b7280', fontWeight: '500' },
  itemPrice: { fontWeight: '900', fontSize: 20, color: '#39ff14', backgroundColor: '#1a1c1c', paddingVertical: 4, paddingHorizontal: 12, borderRadius: 8 },
  adminHeaderSection: { marginBottom: 48 },
  adminSubtitle: { fontSize: 10, fontWeight: '900', letterSpacing: 3.2, textTransform: 'uppercase', color: '#39ff14', marginBottom: 8 },
  adminTitle: { fontSize: 56, fontWeight: '900', lineHeight: 50, letterSpacing: -2.2, textTransform: 'uppercase', color: '#1a1c1c' },
  adminGrid: { marginBottom: 48, gap: 24 },
  ocrUploadCard: { backgroundColor: 'rgba(57, 255, 20, 0.05)', borderRadius: 32, borderWidth: 2, borderStyle: 'dashed', borderColor: '#d1d5db', padding: 48, alignItems: 'center' },
  ocrIcon: { marginBottom: 24 },
  ocrTitle: { fontSize: 20, fontWeight: '900', textTransform: 'uppercase', letterSpacing: -0.4, marginBottom: 8, color: '#1a1c1c' },
  ocrDesc: { fontSize: 10, fontWeight: '700', color: '#9ca3af', textTransform: 'uppercase', letterSpacing: 1.6 },
  statsCard: { backgroundColor: '#1a1c1c', padding: 32, borderRadius: 32, justifyContent: 'space-between' },
  statsLabel: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.6, opacity: 0.6, color: '#fff', marginBottom: 4, marginTop: 16 },
  statsValue: { fontSize: 36, fontWeight: '900', fontStyle: 'italic', color: '#fff' },
  statsBottom: { marginTop: 32 },
  confidenceWrapper: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' },
  confidenceText: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.6, opacity: 0.6, color: '#fff' },
  confidenceValue: { fontSize: 24, fontWeight: '900', color: '#39ff14' },
  confidenceBarBg: { height: 48, width: 6, backgroundColor: 'rgba(255, 255, 255, 0.1)', borderRadius: 4, overflow: 'hidden' },
  confidenceBarFill: { height: '98%', width: '100%', backgroundColor: '#39ff14' },
  inventoryHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 32 },
  inventoryTitle: { fontSize: 24, fontWeight: '900', textTransform: 'uppercase', letterSpacing: -0.4, color: '#1a1c1c' },
  exportBtn: { paddingVertical: 8, paddingHorizontal: 24, backgroundColor: '#e5e7eb', borderRadius: 12 },
  exportBtnText: { color: '#000', fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.6 },
  inventoryList: { gap: 16 },
  inventoryRow: { flexDirection: 'row', alignItems: 'center', padding: 24, borderRadius: 16, backgroundColor: '#1a1c1c' },
  inventoryRowApproved: { backgroundColor: '#f3f4f6' },
  invColMain: { flex: 2 },
  invName: { fontWeight: '900', textTransform: 'uppercase', fontSize: 18, letterSpacing: -0.4, color: '#fff' },
  invCat: { fontSize: 10, textTransform: 'uppercase', color: 'rgba(255, 255, 255, 0.4)' },
  textMuted: { color: '#9ca3af' },
  invColPrice: { flex: 1, textAlign: 'center', fontWeight: '700', color: 'rgba(255, 255, 255, 0.6)' },
  invColRec: { flex: 1, textAlign: 'center', fontWeight: '900', fontSize: 20, fontStyle: 'italic', color: '#39ff14' },
  invColAction: { flex: 1, alignItems: 'flex-end' },
  approvedBadge: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  approvedText: { color: '#9ca3af', fontWeight: '900', fontSize: 10, textTransform: 'uppercase', fontStyle: 'italic' },
  approveBtn: { backgroundColor: '#39ff14', paddingVertical: 8, paddingHorizontal: 20, borderRadius: 12 },
  approveBtnText: { color: '#000', fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.6 },
  menuScrollContent: { paddingBottom: 160 },
  priorityBanner: { backgroundColor: '#39ff14', paddingVertical: 12, paddingHorizontal: 24, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', zIndex: 40, shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.1, shadowRadius: 15, elevation: 5 },
  bannerLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  bannerText: { color: '#000', fontWeight: '900', fontSize: 10, textTransform: 'uppercase', letterSpacing: 1.6 },
  bannerTimer: { backgroundColor: '#000', paddingVertical: 4, paddingHorizontal: 12, borderRadius: 12 },
  bannerTimerText: { color: '#39ff14', fontSize: 10, fontWeight: '900' },
  happyHourBanner: { backgroundColor: '#1a1c1c', paddingVertical: 16, paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: 'rgba(255, 255, 255, 0.05)' },
  hhLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  hhText: { color: '#fff', fontWeight: '900', fontSize: 18, letterSpacing: -0.8, textTransform: 'uppercase', fontStyle: 'italic' },
  hhBadge: { color: '#39ff14', fontSize: 9, fontWeight: '900', letterSpacing: 1.6, backgroundColor: 'rgba(57, 255, 20, 0.1)', paddingVertical: 4, paddingHorizontal: 8, borderRadius: 4, borderWidth: 1, borderColor: 'rgba(57, 255, 20, 0.2)', textTransform: 'uppercase' },
  foodGrid: { paddingHorizontal: 24, gap: 24, paddingBottom: 24 }, // Slightly tighter gap between cards
  foodCard: { backgroundColor: '#1a1c1c', borderRadius: 20, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.15, shadowRadius: 20, elevation: 8, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  foodImgContainer: { height: 180, width: '100%', backgroundColor: '#2f3131', position: 'relative' },
  foodImg: { width: '100%', height: '100%', opacity: 0.95 },
  fastBadgeWrapper: { position: 'absolute', top: 12, left: 12, zIndex: 10 },
  fastBadge: { backgroundColor: '#39ff14', flexDirection: 'row', alignItems: 'center', paddingVertical: 4, paddingHorizontal: 10, borderRadius: 8, gap: 4 },
  fastBadgeText: { color: '#000', fontSize: 10, fontWeight: '900', letterSpacing: 0.5 },
  foodInfo: { padding: 20 },
  foodHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  foodName: { fontWeight: '800', fontSize: 20, letterSpacing: -0.5, textTransform: 'uppercase', color: '#fff', flex: 1, marginRight: 12 },
  foodPrice: { color: '#39ff14', fontWeight: '900', fontSize: 22, letterSpacing: -0.5 },
  foodPricing: { alignItems: 'flex-end' },
  foodOldPrice: { color: 'rgba(255, 255, 255, 0.3)', textDecorationLine: 'line-through', fontSize: 12, fontWeight: '700' },
  foodDesc: { color: '#9ca3af', fontSize: 13, fontWeight: '500', marginBottom: 20, lineHeight: 20 },
  addToTrayBtn: { backgroundColor: '#fff', paddingVertical: 14, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  addToTrayText: { color: '#000', fontWeight: '900', fontSize: 14, letterSpacing: 1 },
  // Replaces checkoutFabContainer and checkoutFab
  checkoutFabContainer: { position: 'absolute', bottom: 108, alignSelf: 'center', zIndex: 50 },
  checkoutFab: { backgroundColor: '#1a1c1c', paddingVertical: 14, paddingHorizontal: 20, borderRadius: 32, flexDirection: 'row', alignItems: 'center', gap: 24, shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.3, shadowRadius: 20, elevation: 15, borderWidth: 1, borderColor: '#39ff14' },
  checkoutFabLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  checkoutText: { color: '#fff', fontWeight: '900', textTransform: 'uppercase', fontSize: 14, letterSpacing: 1 },
  checkoutTotal: { color: '#39ff14', fontWeight: '900', fontSize: 16, letterSpacing: -0.5 },
  cartBadge: { backgroundColor: '#39ff14', color: '#000', fontWeight: '900', fontSize: 13, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, overflow: 'hidden' },
  checkoutAmount: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  checkoutAmountText: { fontSize: 24, letterSpacing: -0.8, fontWeight: '900', color: '#000' },
  menuHeaderContainer: { marginBottom: 24, paddingTop: 16 },
  contextRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  priorityMiniBadge: { backgroundColor: '#39ff14', flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 6, paddingHorizontal: 12, borderRadius: 20 },
  priorityMiniText: { color: '#000', fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1 },
  hhMiniBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 6, paddingHorizontal: 12, backgroundColor: 'rgba(57, 255, 20, 0.1)', borderRadius: 20, borderWidth: 1, borderColor: 'rgba(57, 255, 20, 0.3)' },
  hhMiniText: { color: '#39ff14', fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1 },
  sectionTitle: { fontSize: 32, fontWeight: '900', letterSpacing: -1.5, color: '#1a1c1c', marginBottom: 16, textTransform: 'uppercase' },
  categoryWrapper: { marginHorizontal: -24 }, // Negates parent padding to allow edge-to-edge scroll
  categoryScroll: { paddingHorizontal: 24, gap: 12 },
  categoryPill: { paddingVertical: 10, paddingHorizontal: 20, borderRadius: 24, backgroundColor: '#e5e7eb', borderWidth: 1, borderColor: 'transparent' },
  categoryPillActive: { backgroundColor: '#1a1c1c', borderColor: '#39ff14' },
  categoryText: { fontSize: 12, fontWeight: '800', color: '#6b7280', textTransform: 'uppercase', letterSpacing: 0.5 },
  categoryTextActive: { color: '#39ff14' },
  flatListContent: { paddingBottom: 140 },
  // --- MODAL STYLES ---
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: '#f9f9f9', borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 32, shadowColor: '#000', shadowOffset: { width: 0, height: -10 }, shadowOpacity: 0.1, shadowRadius: 20, elevation: 10 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  modalTitle: { fontSize: 24, fontWeight: '900', textTransform: 'uppercase', letterSpacing: -0.5, color: '#1a1c1c' },
  cartItemRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  cartItemInfo: { flex: 1, paddingRight: 16 },
  cartItemName: { fontSize: 16, fontWeight: '800', color: '#1a1c1c', textTransform: 'uppercase', marginBottom: 4 },
  cartItemPrice: { fontSize: 14, fontWeight: '900', color: '#6b7280' },
  modalTotalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 32, paddingTop: 16, borderTopWidth: 2, borderTopColor: '#1a1c1c' },
  modalTotalLabel: { fontSize: 18, fontWeight: '900', textTransform: 'uppercase', color: '#6b7280' },
  modalTotalValue: { fontSize: 32, fontWeight: '900', color: '#39ff14', backgroundColor: '#1a1c1c', paddingHorizontal: 16, paddingVertical: 4, borderRadius: 8 },
  payButton: { backgroundColor: '#39ff14', paddingVertical: 20, borderRadius: 16, alignItems: 'center', shadowColor: '#39ff14', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.3, shadowRadius: 20, elevation: 10 },
  payButtonText: { fontSize: 16, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 2, color: '#000' },
  qtyControl: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f3f4f6', borderRadius: 24, padding: 4, borderWidth: 1, borderColor: '#e5e7eb' },
  qtyBtn: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff', borderRadius: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 2 },
  qtyText: { width: 32, textAlign: 'center', fontSize: 14, fontWeight: '900', color: '#1a1c1c' },
});